apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-soknad-frontend
  namespace: min-side
  labels:
    team: min-side
spec:
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /minside/soknad/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /minside/soknad/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      external:
        - host: sokos-kontoregister-person.intern.nav.no  
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
    - "https://www.nav.no/minside/soknad"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
